@startuml
'https://plantuml.com/class-diagram

enum UserStatus {
    ONLINE
    OFFLINE
}

enum CityCategory {
    EUROPE
    ASIA
    NORTH_AMERICA
}

class User {
    - userId: long
    - username: String
    - password: String
    - userStatus: UserStatus
    - createDay: Date
    - birthDay: Date
    + userStatistics: UserStatistics
    + User(String name, String password)
    + getUserId(): long
    + getUsername(): String
    + setUsername(String name): void
    + getPassword(): String
    + setPassword(String password): void
    + getUserStatus(): UserStatus
    + setUserStatus(UserStatus status): void
    + getUserCreateDay(): Date
    + getUserBirthDay(): Date
    + setUserBirthDay(Date birthday): void
}

class Player {
    - userId: long
    - playerName: String
    - score: int
    - answerList: List<String>
    + Player(long userId, String name)
    + getUserId(): long
    + getPlayerName(): String
    + getScore(): int
    + addScore(int score): void
    + addAnswer(String answer): void
}

class UserStatistics {
    - totalScore: long
    - totalGameNum: long
    - specificScore: Map<CityCategory, Long>
    - gameHistories: List<UserGameHistory>
    + UserStatistics()
    + getTotalScore(): long
    + getSpecificScore(CityCategory category): long
    + updateScore(long score, CityCategory category): void
    + getTotalGameNum(): long
    + addTotalGameNum(): void
    + getGameHistoryList(): Iterator<UserGameHistory>
    + addGameHistory(UserGameHistory history): void
}

class UserGameHistory {
    - gameId: long
    - gameInfo: GameInfo
    - gameScore: int
    - answerList: List<String>
    + UserGameHistory(long gameId, GameInfo gameInfo,
      int score)
    + getGameId(): long
    + getScore(): int
    + getGameInfo(): GameInfo
    + addAnswer(String answer): void
    + getAnswerList(): Iterator<String>
}

User <-- UserStatistics
UserStatus -> User
UserStatistics *-- UserGameHistory


class Game {
    - playerList: List<Player>
    - currentRound: int
    - totalRounds: int
    - countdownTime: int
    + cityDB: CityBase
    + Game(int totalRounds, int countdownTime, CityBase cityDB)
    + addPlayer(User userAsPlayer): void
    + getCurrentRounds(): int
    + getTotalRounds(): int
    + getCountdownTime(): int
    + showRanking(): void
}

class CityBase {
    - category: CityCategory
    - cityList: List<City>
    + CityBase(CityCategory category)
    + getCategory(): CityCategory
    - loadCityList(): void
    + getCityListLength(): int
    + drawCities(): List<City>
}

class GameInfo {
    - gameId: long
    - gameCategory: CityCategory
    - gameTime: Date
    - gameRounds: int
    - playerNum: int
    - labelList: List<String>
    + GameInfo(long gameId, CityCategory category,
      int gameRound, int playerNum)
    + getCategory(): CityCategory
    + getGameTime(): Date
    + getPlayerNum(): int
    + getGameRound(): int
    + addLabel(String label): void
    + getLabelList(): Iterator<String>
}

class City {
    - name: String
    - country: String
    - location: String
    + City(String name, String country, String location)
    + getName(): String
    + getCountry(): String
    + getLocation(): String
    + generatePicture(): Picture
}

'class Picture {
'    - pictureId: long
'    - picturePath: String
'    + Picture(long pictureId, String path)
'    + getPictureId(): long
'    + getPicturePath(): String
'}

Player <-- User
Player -o Game

Game <-- CityBase
CityBase o-- City
CityBase <-- CityCategory
UserStatistics <- CityCategory
CityCategory --> GameInfo
UserGameHistory <- GameInfo

'CityCategory <|-- EuroCity
'CityCategory <|--- AsiaCity
'CityCategory <|--- NorthAmericaCity
'CityCategory <|---- WorldCity

@enduml